# Generated by Django 3.0.6 on 2020-05-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('r_gas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Тариф за Газ')),
                ('r_light', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Тариф за Свет')),
                ('r_water', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Тариф за Вода')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_rec', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('gas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Газ')),
                ('light', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Свет')),
                ('water', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вода')),
            ],
            options={
                'verbose_name': 'Показания',
                'verbose_name_plural': 'Общие показания',
                'ordering': ['-when_rec'],
            },
        ),
        migrations.CreateModel(
            name='UsersSNT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.EmailField(max_length=254, verbose_name='Логин')),
                ('parole_user', models.PositiveSmallIntegerField(verbose_name='Пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name_user', models.CharField(db_index=True, max_length=254, verbose_name='Имя члена СНТ')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Список пользователей',
                'ordering': ['name_user'],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_rec', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('gas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Газ')),
                ('light', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Свет')),
                ('water', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вода')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meter.UsersSNT', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Показания',
                'verbose_name_plural': 'Показания',
                'ordering': ['-when_rec'],
            },
        ),
    ]
